// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID         *int    `json:"id,omitempty"`
	Name       *string `json:"name,omitempty"`
	Price      *int    `json:"price,omitempty"`
	Stock      *int    `json:"stock,omitempty"`
	Author     *string `json:"author,omitempty"`
	Examplar   *int    `json:"examplar,omitempty"`
	Sellerid   *int    `json:"sellerid,omitempty"`
	Categoryid *int    `json:"categoryid,omitempty"`
}

type Category struct {
	ID          *int    `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

type Order struct {
	ID     *int  `json:"id,omitempty"`
	Paid   *bool `json:"paid,omitempty"`
	Total  *int  `json:"total,omitempty"`
	Userid *int  `json:"userid,omitempty"`
}

type OrderItem struct {
	ID       *int `json:"id,omitempty"`
	Quantity *int `json:"quantity,omitempty"`
	Orderid  *int `json:"orderid,omitempty"`
	Bookid   *int `json:"bookid,omitempty"`
	Price    *int `json:"price,omitempty"`
	Subtotal *int `json:"subtotal,omitempty"`
	Userid   *int `json:"userid,omitempty"`
}

type User struct {
	Name     *string `json:"name,omitempty"`
	Email    *string `json:"email,omitempty"`
	Username *string `json:"username,omitempty"`
	Password *string `json:"password,omitempty"`
}
