// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Price      int    `json:"price"`
	Stock      int    `json:"stock"`
	Author     string `json:"author"`
	Examplar   int    `json:"examplar"`
	Sellerid   int    `json:"sellerid"`
	Categoryid int    `json:"categoryid"`
}

type Category struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Order struct {
	ID     string `json:"id"`
	Paid   bool   `json:"paid"`
	Total  int    `json:"total"`
	Userid int    `json:"userid"`
}

type OrderItem struct {
	ID       string `json:"id"`
	Quantity int    `json:"quantity"`
	Orderid  int    `json:"orderid"`
	Bookid   int    `json:"bookid"`
	Price    int    `json:"price"`
	Subtotal int    `json:"subtotal"`
	Userid   int    `json:"userid"`
}

type User struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
}
