kind: ReplicationController
apiVersion: v1
metadata:
  name: bookserv
  labels:
    app: bookserv
    owner: github.com/rulanugrh
spec:
  replicas: 3
  selector:
    app: bookserv
  template:
    metadata:
      labels:
        app: bookserv
    spec:
      containers:
      - name: bookserv-container
        image: kyzxo/bookserv:v1
        ports:
          - name: book-server
            containerPort: 3000