version: '3'
services:

  api-gateway:
    image: nginx
    container_name: api-gateway
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - alphanetwork
    
  book-services:
    build:
      context: ./book-services/
      dockerfile: ./book-services/Dockerfile
    environment:
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
    ports:
      - 3000:3000
    depends_on:
      - db-book
    networks:
      - alphanetwork
  
  db-book:
    container_name: db-book
    image: mysql
    environment:
      - MYSQL_NAME=${MYSQL_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
    ports:
      - 3306:3306
    networks:
      - alphanetwork
  
  msgbroker:
    container_name: msgbroker
    image: rabbitmq:3.9.11-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - alphanetwork

networks:
  alphanetwork: