#!/bin/bash
command=$1
if (( $command == app ))
then
    docker-compose up -d --env-file .env up -d
    exit
else if (( $command == require ))
then
    sudo apt install docker docker.io docker-compose -y
    exit 0
else
    echo "command error, read documentation"
    exit
fi