kind: ReplicationController
apiVersion: v1
metadata:
  name: mysql-book
  labels:
    app: bookserv
    role: db-data
spec:
  replicas: 1
  selector:
    app: bookserv
    role: db-data
  template:
    metadata:
      labels:
        app: bookserv
        role: db-data
      data:
    spec:
      containers:
      - name: mysql-book
        image: registry.k8s.io/redis:e2e
        ports:
        - name: mysql-book-server
          containerPort: 3306

---
kind: Service
apiVersion: v1
metadata:
  name: mysql-book
  labels:
    app: bookserv
    owner: github.com/rulanugrh
    role: mysql-book
spec:
  ports:
    - port: 3306
      targetPort: mysql-book-server
  selector:
    app: bookserv
    role: mysql-book
  type: LoadBalancer